name:                runa
version:             0.1.0.0
github:              "Player-205/runa"
license:             BSD3
author:              "Andrei Borzenkov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Player-205/runa#readme>

default-extensions:
- OverloadedStrings
- ImportQualifiedPost

dependencies:
- base >= 4.7 && < 5
- typed-process
- HsYAML
- directory
- text
- bytestring
- filepath

library:
  source-dirs: src

executables:
  runa:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - runa

tests:
  runa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - runa
