module CreateProject where



import Data.YAML
import Config
import System.Directory 
import System.FilePath
import Data.ByteString qualified as BS


createProject name = do
  projDir <- makeAbsolute name
  createDirectoryIfMissing False projDir
  createDirectory (projDir </> "app")
  BS.writeFile (projDir </> "app" </> "main.fut") defaultProgram
  BS.writeFile (projDir </> "package.yaml") (encode1Strict defaultConfig <> "\n# cuda-path: /usr/local/cuda-11.4")



defaultProgram :: BS.ByteString
defaultProgram = mconcat 
  [ "-- Default module, generated by runa!\n\n"
  
  , "let main (x: i32) (y: i32) : i32 = x + y"
  ]
